<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ModificarVenta.aspx.cs" Inherits="MaestroDetalleEntidad.ModificarVenta" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 100%;
        }
        .auto-style2 {
        }
        .auto-style3 {
            width: 66px;
        }
        .auto-style5 {
            width: 168px;
        }
        .auto-style6 {
            width: 65px;
            height: 26px;
        }
        .auto-style7 {
            width: 66px;
            height: 26px;
        }
        .auto-style9 {
            width: 168px;
            height: 26px;
        }
        .auto-style10 {
            height: 26px;
        }
        .auto-style12 {
            height: 90px;
        }
        .auto-style13 {
            width: 168px;
            height: 90px;
        }
        .auto-style14 {
            width: 20px;
        }
        .auto-style15 {
            height: 26px;
            width: 20px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <table class="auto-style1">
            <tr>
                <td colspan="4" style="padding: inherit; margin: inherit; font-family: Arial; font-size: large; color: #008000">EDICION DE VENTAS</td>
                <td style="padding: inherit; margin: inherit; font-family: Arial; font-size: large; color: #008000">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style2">&nbsp;</td>
                <td class="auto-style3">&nbsp;</td>
                <td class="auto-style14">&nbsp;</td>
                <td class="auto-style5">&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style6">
                    <asp:Label ID="Label1" runat="server" Font-Bold="True" Text="Id:"></asp:Label>
                </td>
                <td class="auto-style7">
                    <asp:TextBox ID="TextBox1" runat="server" Enabled="False"></asp:TextBox>
                </td>
                <td class="auto-style15">
                    <asp:Label ID="Label2" runat="server" Font-Bold="True" Text="Fecha:"></asp:Label>
                </td>
                <td class="auto-style9">
                    <asp:TextBox ID="TextBox2" runat="server" TextMode="Date" Width="109px"></asp:TextBox>
                </td>
                <td class="auto-style10"></td>
            </tr>
            <tr>
                <td class="auto-style2">
                    <asp:Label ID="Label3" runat="server" Font-Bold="True" Text="Cliente:"></asp:Label>
                </td>
                <td class="auto-style3">
                    <asp:ListBox ID="ListBox1" runat="server" Height="98px" Width="153px"></asp:ListBox>
                </td>
                <td class="auto-style14">
                    <asp:Button ID="Button2" runat="server" BackColor="#339933" ForeColor="White" Height="38px" OnClick="Button2_Click" Text="Clientes" Width="82px" />
                </td>
                <td class="auto-style5">&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style12">
                    <asp:Label ID="Label4" runat="server" Font-Bold="True" Text="Glosa:"></asp:Label>
                </td>
                <td class="auto-style12" colspan="2">
                    <asp:TextBox ID="TextBox3" runat="server" Height="80px" TextMode="MultiLine" Width="229px"></asp:TextBox>
                </td>
                <td class="auto-style13"></td>
                <td class="auto-style12"></td>
            </tr>
            <tr>
                <td class="auto-style2">&nbsp;</td>
                <td class="auto-style3">
                    <asp:Button ID="Button3" runat="server" BackColor="#FF6600" Font-Bold="True" ForeColor="White" Height="38px" OnClick="Button3_Click" Text="Productos" Width="82px" />
                </td>
                <td class="auto-style14">&nbsp;</td>
                <td class="auto-style5">&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style2" colspan="5">
                    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" ForeColor="#333333" GridLines="None" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" Width="637px">
                        <AlternatingRowStyle BackColor="White" />
                        <Columns>
                            <asp:BoundField DataField="Id" HeaderText="Id" />
                            <asp:BoundField DataField="IdProducto" HeaderText="Id" />
                            <asp:BoundField DataField="Nombre" HeaderText="Nombre" />
                            <asp:BoundField DataField="Cantidad" HeaderText="Cantidad" />
                            <asp:BoundField DataField="Precio" HeaderText="Precio" />
                            <asp:BoundField DataField="Monto" HeaderText="Monto" />
                        </Columns>
                        <EditRowStyle BackColor="#7C6F57" />
                        <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                        <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
                        <RowStyle BackColor="#E3EAEB" />
                        <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
                        <SortedAscendingCellStyle BackColor="#F8FAFA" />
                        <SortedAscendingHeaderStyle BackColor="#246B61" />
                        <SortedDescendingCellStyle BackColor="#D4DFE1" />
                        <SortedDescendingHeaderStyle BackColor="#15524A" />
                    </asp:GridView>
                </td>
            </tr>
            <tr>
                <td class="auto-style2">&nbsp;</td>
                <td class="auto-style3">&nbsp;</td>
                <td class="auto-style14">&nbsp;</td>
                <td class="auto-style5">&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style2">&nbsp;</td>
                <td class="auto-style3">&nbsp;</td>
                <td class="auto-style14">
                    <asp:Label ID="Label5" runat="server" Text="Total:"></asp:Label>
                </td>
                <td class="auto-style5">
                    <asp:Label ID="Label6" runat="server" Font-Bold="True" Text="0"></asp:Label>
                </td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style2">&nbsp;</td>
                <td class="auto-style3">
                    <asp:Label ID="Label7" runat="server" ForeColor="Red" Text="Label" Visible="False"></asp:Label>
                </td>
                <td class="auto-style14">&nbsp;</td>
                <td class="auto-style5">&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style2">&nbsp;</td>
                <td class="auto-style3">
                    <asp:Button ID="Button1" runat="server" BackColor="#660066" ForeColor="White" OnClick="Button1_Click" Text="Guardar" style="height: 26px" />
                </td>
                <td class="auto-style14">&nbsp;</td>
                <td class="auto-style5">&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
        </table>
    
    </div>
    </form>
</body>
</html>

