//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaestroDetalleEntidad.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public Venta()
        {
            this.DetalleVenta = new HashSet<DetalleVenta>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string glosa { get; set; }
        public Nullable<int> IdCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<DetalleVenta> DetalleVenta { get; set; }
    }
}
